{
  "agent": {
    "region": "{{region_name}}"
  },
  "metrics": {
    "metrics_collected": {
      "cpu": {
        "measurement": [
          "cpu_usage_idle",
          "cpu_usage_iowait",
          "cpu_usage_user",
          "cpu_usage_system"
        ],
        "metrics_collection_interval": 60,
        "resources": ["*"]
      },
      "mem": {
        "measurement": [
          "mem_used_percent"
        ],
        "metrics_collection_interval": 60,
        "resources": ["*"]
      },
      "disk": {
        "measurement": [
          "used_percent"
        ],
        "metrics_collection_interval": 60,
        "resources": ["*"]
      },
      "net": {
        "metrics_collection_interval": 60,
        "resources": ["*"]
      },
      "kubernetes": {
        "cluster_name": "{{cluster_name}}",
        "metrics_collection_interval": 60
      }
    },
    "force_flush_interval": 5
  }
}
