apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zk-storageclass
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd 
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - us-east1-d
