---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-1
  labels:
    pv-type: rabbitmq
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  # Other PV specifications...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
  selector:
    matchLabels:
      pv-type: rabbitmq
