apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: my-rabbitmq-cluster
spec:
  replicas: 3
  image: rabbitmq:3.9.10-management
  service:
    type: NodePort
    ports:
      - name: http
        protocol: TCP
        port: 15672
        targetPort: 15672
      - name: amqp
        protocol: TCP
        port: 5672
        targetPort: 5672
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi
